"""CH02EP16 (ROKS Cheonan) clips 13-112: authored Omni chain plan (continues the 2-min sample, clips 1-12).

    py -3.12 build_CH02EP16_013-112.py      -> CH02EP16_omni_plan_013-112.json + rendered prompts

Scene SETS carry the environment, cast (exact counts), lighting, rigid rules and negatives; each CLIP picks a
set, a camera plan and timestamped beats. A clip with "chg" changes scene at that second through a camera
bridge (the first beat after "chg" must describe the bridge); the builder then writes the environment as
"old -- then -- new" and the cast as "old (until t); then new". One change per clip max, never in the last 3 s.
Beat times follow the sentence starts in CH02EP16_omni_GATE2A.md (estimate after 146 s; the assembler retimes).
"""
import json, pathlib, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
CORVETTE = "low sleek grey 88-metre hull, one small gun on the foredeck, a single lattice mast, no hull numbers"
NIGHT = "night: faint moonlight through thin cloud, deep night blues, crushed blacks"
BENTHIC = "Deep benthic palette: pitch black water beyond harsh torch cones, muddy grey silt, suspended marine snow"
OVERCAST = "Overcast maritime palette: flat slate-grey sky, iron-grey sea, rust-streaked steel, salt spray"
INTERIOR = "Interior mechanical palette: dark matte grey steel, amber tungsten instrument spill, soft green display glow"
DESK = "Document-table palette: neutral surface, one hard directional lamp, matte steel, no colour cast beyond the lamp"
NO_SCREEN_TEXT = "no readable screens, no numbers, no letters on displays or consoles"

SETS = {
    "standoff": dict(env="the calm sea at nightfall: the corvette's silhouette with two dim lights far away on the left, a small dark patrol boat far away on the right, wide empty water between them",
                     cast="exactly two vessels, both distant silhouettes; no people visible", light="nightfall, deep blue-grey sky, dark calm water",
                     neg="no gunfire, no muzzle flashes, no explosions"),
    "patrol_night": dict(env="the grey corvette cruising at steady speed on calm black sea at night, a few dim amber deck lights",
                         cast=f"exactly one corvette ({CORVETTE}); small crew silhouettes on deck at most, faces never visible", light=NIGHT + ", a few dim amber deck lights"),
    "bridge": dict(env="the dim bridge of the corvette at night: steel consoles, a wide dark window onto the black sea, one round green radar display with a slow sweeping line",
                   cast="exactly two crew silhouettes seen from behind at the consoles, faces never visible", light=INTERIOR, neg=NO_SCREEN_TEXT),
    "sonar": dict(env="a cramped dark sonar compartment: one console with a round green display showing only a soft sweeping line and faint grainy noise, cables along grey steel",
                  cast="exactly one sonar operator seen from behind, headphones on, face never visible", light=INTERIOR, neg=NO_SCREEN_TEXT),
    "patrol_day": dict(env="the grey corvette cruising slowly between small rocky islets in shallow green-grey coastal water under an overcast sky",
                       cast=f"exactly one corvette ({CORVETTE}); no people visible", light=OVERCAST),
    "sub": dict(env="near-dark shallow water just above an uneven rocky seabed with boulders and silt",
                cast="exactly one small dark midget submarine (about 30 m long, rounded hull, small fin, one propeller, no markings); no people",
                light="near darkness, faint blue light from the surface far above, suspended particles",
                rigid="the submarine keeps its exact shape and size and moves slowly and steadily", neg="no torpedo launch, no markings, no divers"),
    "sub_under": dict(env="dark water near the seabed; far above, the huge dark hull of the corvette passes along the pale surface",
                      cast="exactly one small dark midget submarine near the seabed and exactly one corvette hull far above; no people",
                      light="near darkness, faint blue light from the surface", rigid="both hulls keep their exact shape and size", neg="no torpedo launch, no markings"),
    "blast": dict(env="the night sea: the corvette seen side-on at a distance on calm black water; beside her stern a column of white water rises and falls exactly as the beats describe",
                  cast=f"exactly one corvette ({CORVETTE}); no people visible", light=NIGHT,
                  neg="no fire, no flash, no fireball, no debris, no people in the water"),
    "broken": dict(env="the night sea after the blast: the corvette's two separate hull sections, the bow section still afloat and tilted, the stern section low in the water, drifting mist",
                   cast="exactly two hull sections of one ship; at most a few sailor silhouettes in life vests on the bow, faces never visible",
                   light=NIGHT, neg="no fire, no bodies, no blood, no explosion flash"),
    "rescue": dict(env="the night sea around the floating bow section: hard white searchlight beams sweeping the black water, cold mist",
                   cast="the floating bow section; exactly two small rescue boats with silhouetted crews in life vests; exactly one rescue helicopter; faces never visible",
                   light="night: hard white searchlight beams, dark water, cold mist", neg="no bodies, no blood, no fire"),
    "seabed_stern": dict(env="the dark seabed about 45 m down: the broken stern section of the corvette lying on muddy grey silt, torn steel edges, a debris field around it",
                         cast="the stern section; exactly two divers seen from behind, masks on, faces never visible", light=BENTHIC,
                         rigid="the stern section is rigid and never moves", neg="no bodies, no readable markings"),
    "salvage": dict(env="overcast grey sea by day: a large floating crane barge with a tall crane and heavy cables above the wreck site, small workboats nearby",
                    cast="exactly one crane barge, exactly two small workboats, silhouetted workers in hard hats on deck, faces never visible", light=OVERCAST,
                    neg="no text or numbers on the barge, no flags"),
    "table": dict(env="a plain evidence table under one hard lamp: a torn, outward-bent piece of grey hull steel, metal fragments and a coil of wire in clear plastic bags with blank white tags, a steel ruler, calipers",
                  cast="no people, no hands", light=DESK, rigid="every object on the table is rigid and stays in place",
                  neg="no writing on tags or bags, no readable documents"),
    "dock": dict(env="a grey naval dock under an overcast sky: the bow and stern sections of the broken corvette laid out on blocks side by side on the quay, a wide clean gap between them",
                 cast="exactly two hull sections; small investigator silhouettes in coats, faces never visible", light=OVERCAST,
                 rigid="the hull sections are rigid and never move", neg="no hull numbers, no text, no flags"),
    "command": dict(env="a dim naval command room at night: a large table with a plain unmarked dark-grey relief model of the island and the seabed, one low lamp",
                    cast="exactly four officer silhouettes standing around the table, faces never visible", light=INTERIOR,
                    neg="no paper, no maps, no charts, no screens, no text or numbers anywhere, no flags"),
    "island_aerial": dict(env="high above the grey sea at dawn: a low barren rocky island below, and far away on the horizon a long dark coastline",
                          cast="exactly two tiny patrol boats far apart on the water; no people visible", light="overcast dawn, soft grey light, haze on the horizon"),
    "mine": dict(env="murky grey-green water: an old rusted spiked sea mine swaying slowly on its chain above the silt",
                 cast="exactly one sea mine; no people, no divers", light="murky filtered light, suspended particles",
                 rigid="the mine keeps its exact shape; it never explodes"),
    "underhull": dict(env="underwater at night beneath the long dark hull of a ship seen from below, still black water",
                      cast="one ship's hull seen from below; no people", light="near darkness, faint blue light from the surface",
                      rigid="the hull is rigid", neg="no fire, no flash, no debris"),
    "bubble": dict(env="underwater at night beneath the dark keel of a ship seen from below; in the black water below the keel one gas bubble grows and collapses exactly as the beats describe",
                   cast="one ship's hull seen from below and exactly one gas bubble; no people",
                   light="near darkness, the bubble lit from within by a soft pale glow",
                   rigid="the hull stays rigid except at the one point where the water jet strikes", neg="no fire, no flash, no debris, no torpedo visible"),
    "seabed_debris": dict(env="the muddy seabed in torch light: a scattered debris field of small twisted metal fragments, wire and machined parts, small yellow marker buoys on the silt",
                          cast="exactly two divers seen from behind, faces never visible", light=BENTHIC, neg="no readable markings"),
    "torpedo_run": dict(env="dark open water: a long dark torpedo gliding silently, a faint trail of tiny bubbles behind its propeller",
                        cast="exactly one torpedo; no people", light="near darkness, faint blue light from the surface",
                        rigid="the torpedo keeps its exact shape and size", neg="no explosion, no markings, no text"),
    "torpedo": dict(env="the muddy grey seabed in a diver's torch beam: a corroded cylindrical torpedo propulsion section with a small crusted propeller half-buried in silt",
                    cast="exactly one or two divers seen from behind, faces hidden; one propulsion section", light=BENTHIC,
                    neg="no readable writing, no characters, no letters"),
    "lab": dict(env="a grey investigation hangar: the corroded torpedo propulsion section resting on a padded stand under hard work lights, a faint smudge of blue ink on its inner casing, blurred and illegible",
                cast="the propulsion section; exactly two investigator silhouettes in the background, faces never visible", light=DESK,
                rigid="the propulsion section is rigid", neg="no readable writing, no characters, no letters"),
    "report": dict(env="a plain press briefing room: a long table with a closed thick bound report with a blank cover, a row of microphones, blurred rows of seated reporters beyond",
                   cast="no speaker; blurred reporter silhouettes, faces never visible", light="flat bright room light, neutral tones",
                   neg="no readable text, no flags, no logos, no screens with text, no camera flashes"),
    "radio": dict(env="a dark room: an old radio receiver with a softly glowing amber dial on a wooden table",
                  cast="no people", light="one warm amber glow in darkness", rigid="the radio is rigid; its glow is steady", neg="no readable dial text, no flicker"),
    "study": dict(env="a quiet study at night: a desk lamp, a closed thick report with a plain blank cover, a small grey scale model of the broken corvette hull on the desk",
                  cast="exactly one academic silhouette seen from behind at the desk, face never visible", light=DESK,
                  neg="no loose papers, no open pages, no diagrams, no screens, no text anywhere"),
    "un": dict(env="a wide circular council chamber in soft daylight: a large horseshoe-shaped table with rows of chairs and microphones, tall windows",
               cast="no people close; only blurred distant silhouettes, faces never visible", light="soft daylight, neutral tones",
               neg="no flags, no emblems, no readable text, no name plates"),
    "memorial": dict(env="calm grey sea at dusk off a low barren island, a single white wreath of flowers floating on the water",
                     cast="exactly one wreath; no people, no ships", light="overcast dusk, fading grey light"),
}

# (set, camera, action, beats, chg)  chg = second the scene changes (bridge), else None
C = [
 ("standoff", "slow rising crane move above the dark sea between the two ships", "past clashes hang over these waters",
  [("00:00-00:03", "the searchlight beam from the far patrol boat sweeps back and forth once more, then goes dark"),
   ("00:03-00:07", "the two distant ships hold position, dark and still, across the empty water"),
   ("00:07-00:10", "the camera starts to glide down toward the corvette's silhouette")], None),
 ("patrol_night", "a slow glide toward the corvette that becomes a lateral tracking move along her at deck height", "Cheonan on her patrol rotation",
  [("00:00-00:02.5", "the camera glides low over the black water toward the corvette"),
   ("00:02.5-00:06.5", "tracking along her grey hull at deck height; a few dim amber deck lights"),
   ("00:06.5-00:10", "small crew silhouettes walk slowly along the deck railing, faces never visible")], None),
 ("bridge", "the tracking move rises to the bridge windows, then a slow push-in inside the dim bridge", "a normal night watch",
  [("00:00-00:02", "the tracking continues along the dark hull toward the lit bridge windows"),
   ("00:02-00:03.5", "without any cut the camera rises to the bridge windows and glides through the glass into the dim bridge"),
   ("00:03.5-00:06.5", "two crew silhouettes stand at the consoles; a round green radar display sweeps slowly"),
   ("00:06.5-00:10", "through the wide dark window the calm black sea slides by")], 2.0),
 ("bridge", "slow push-in past the two crew toward the radar display", "no warning of anything different",
  [("00:00-00:03", "one crewman leans toward the radar display, calm and still"),
   ("00:03-00:08", "the radar line sweeps over an empty green screen; nothing appears on it"),
   ("00:08-00:10", "the push-in continues toward the dark window")], None),
 ("sub", "a glide out through the dark window and down beneath the surface, then a slow descent toward the seabed", "the hunter below the hunter",
  [("00:00-00:00.5", "the push-in reaches the dark window"),
   ("00:00.5-00:02", "without any cut the camera glides out through the window and down into the black water beneath the ship"),
   ("00:02-00:04", "near darkness below the keel; the corvette's hull a faint shape above"),
   ("00:04-00:10", "far below near the rocky seabed a small dark midget submarine glides slowly and silently in the same direction")], 0.5),
 ("patrol_day", "a steady rise to the surface, then a low tracking move along the corvette's waterline", "built for shallow coastal water",
  [("00:00-00:01.5", "without any cut the camera rises steadily to the surface and breaks through into grey overcast daylight"),
   ("00:01.5-00:06.5", "the corvette threads slowly between small rocky islets in shallow green-grey water"),
   ("00:06.5-00:10", "the camera tracks low along her waterline; dark rocks show just beneath the surface")], 0.0),
 ("sub", "the tracking move dips beneath the surface into a slow glide over the cluttered seabed", "a small submarine hides in the clutter",
  [("00:00-00:02", "the tracking continues along the waterline past the rocks"),
   ("00:02-00:03.5", "without any cut the camera dips beneath the surface into murky water"),
   ("00:03.5-00:08", "a slow glide over a cluttered rocky seabed; between two boulders a small dark submarine lies still, almost invisible"),
   ("00:08-00:10", "the glide continues past it")], 2.0),
 ("sonar", "the glide rises into darkness that opens onto the sonar compartment, then a slow push-in", "the acoustic picture is quiet",
  [("00:00-00:01.5", "without any cut the camera rises into darkness; the darkness opens onto a dim sonar compartment"),
   ("00:01.5-00:06.5", "the sonar operator sits still, headphones on; the round green display shows only a soft sweeping line and faint noise"),
   ("00:06.5-00:10", "slow push-in to the display; nothing appears on it")], 0.0),
 ("blast", "a slow pull-back out of the compartment into the night, then a steady lateral drift at wave height", "21:22 - the explosion",
  [("00:00-00:01.5", "the push-in continues on the quiet green display"),
   ("00:01.5-00:03", "without any cut the camera pulls back through the darkness and the view opens onto the night sea: the corvette at a distance"),
   ("00:03-00:07", "a tall white column of seawater rises silently beside her stern"),
   ("00:07-00:10", "the column keeps climbing slowly into the night air")], 1.5),
 ("blast", "the same steady lateral drift at wave height", "not internal, not a collision - a force from below",
  [("00:00-00:04", "the column of water hangs in the air; the sea around the stern churns white"),
   ("00:04-00:08.5", "the column falls back into the sea as drifting mist; the corvette's lights go out"),
   ("00:08.5-00:10", "the mist drifts across the dark water")], None),
 ("broken", "the lateral drift continues slowly through the thinning mist", "the corvette broke in two",
  [("00:00-00:01.5", "without any cut the mist thins and reveals the aftermath"),
   ("00:01.5-00:07", "two separate hull sections: the bow section afloat and tilted, the stern section low in the water"),
   ("00:07-00:10", "the stern section settles lower until only its top edge shows; the camera keeps drifting")], 0.0),
 ("broken", "slow lateral drift at wave height along the tilted bow section", "those on deck survived",
  [("00:00-00:06", "close along the tilted bow section: dark open hatches, black water lapping at the deck edge"),
   ("00:06-00:10", "exactly four sailor silhouettes in life vests hold the railing on the high side of the bow, faces never visible")], None),
 ("rescue", "the drift widens into a slow pull-back as searchlights sweep in", "chaos in the first minutes",
  [("00:00-00:02.5", "the four silhouettes hold the railing; water laps below them"),
   ("00:02.5-00:04", "without any cut a searchlight beam sweeps across the frame and the view widens"),
   ("00:04-00:10", "two small rescue boats with silhouetted crews approach the floating bow section through the dark, searchlights sweeping")], 2.5),
 ("rescue", "slow rising move above the rescue scene", "no one knew what caused it",
  [("00:00-00:06", "a rescue helicopter hovers above, its searchlight circling the black water"),
   ("00:06-00:10", "the searchlight passes over empty dark water around the bow section")], None),
 ("rescue", "slow lateral drift along the waterline of the bow section", "too precise for an accident",
  [("00:00-00:04", "a searchlight lingers on the tilted bow section"),
   ("00:04-00:10", "the beam moves slowly along the waterline to where the bow section ends in torn steel")], None),
 ("rescue", "slow push-in toward a rescue boat beside the bow", "fifty-eight rescued, forty-six lost",
  [("00:00-00:07", "rescuers in a small boat help silhouetted sailors down from the bow section's railing into the boat"),
   ("00:07-00:10", "the boat pulls slowly away; a searchlight lingers on the dark, empty water")], None),
 ("seabed_stern", "a sinking descent beneath the surface, then a slow glide down toward the seabed", "the stern settles on the seabed; divers go down",
  [("00:00-00:01", "the searchlights keep sweeping the dark water"),
   ("00:01-00:02.5", "without any cut the camera sinks beneath the black surface"),
   ("00:02.5-00:05.5", "far below in torch-lit darkness the broken stern section rests on the muddy seabed, silt settling around it"),
   ("00:05.5-00:10", "from above, a diver descends on a rope line into the dark water, torch beam cutting through marine snow")], 1.0),
 ("seabed_stern", "slow glide along the stern section", "searching flooded compartments in cold, strong current",
  [("00:00-00:03", "two divers reach the stern section and shine their torches into a dark flooded hatch"),
   ("00:03-00:06.5", "silt streams sideways across the torch beams in a strong current; the divers hold on to the torn hull"),
   ("00:06.5-00:10", "the torch beams search the black interior; nothing moves")], None),
 ("seabed_stern", "slow pull-back from the stern section", "the ship was gone",
  [("00:00-00:04", "the divers' torches fade as the camera pulls back from the stern section into the dark"),
   ("00:04-00:10", "the whole broken stern lies alone on the seabed, its torn edge facing the camera, marine snow falling")], None),
 ("seabed_stern", "slow push-in toward the torn edge", "what weapon could do this",
  [("00:00-00:06.5", "slow push-in toward the torn, jagged edge of the stern section in faint light"),
   ("00:06.5-00:10", "the push-in continues along the torn steel")], None),
 ("island_aerial", "a steady rise up through the water and high into the dawn sky, then a slow aerial drift", "the location mattered",
  [("00:00-00:01.5", "without any cut the camera rises up through the dark water, through the surface and high into the grey dawn sky"),
   ("00:01.5-00:07", "high aerial view: the low barren island below, a dark coastline far away on the horizon"),
   ("00:07-00:10", "slow aerial drift toward the horizon; two tiny patrol boats sit far apart on the grey water")], 0.0),
 ("island_aerial", "a slow aerial glide lower toward the two boats", "contact usually means warning shots and ramming",
  [("00:00-00:04.5", "the camera glides lower as the two small patrol boats turn slowly toward each other, wakes curving"),
   ("00:04.5-00:10", "they stop far apart and hold position; the grey water between them is empty and calm")], None),
 ("mine", "the aerial glide tilts down and sinks beneath the surface, then a slow drift toward the mine", "a mine hits by chance - this blast was aimed",
  [("00:00-00:04", "the two boats hold position far apart on the calm water"),
   ("00:04-00:05.5", "without any cut the camera tilts down and sinks beneath the surface into murky water"),
   ("00:05.5-00:10", "an old rusted spiked sea mine sways slowly on its chain in the murk, going nowhere")], 4.0),
 ("command", "the murk darkens into a dim command room, then a slow push-in toward the table with the relief model", "a choice for naval command",
  [("00:00-00:01.5", "without any cut the murky water darkens and opens onto a dim command room"),
   ("00:01.5-00:07.5", "slow push-in toward four officer silhouettes standing around a large table with a plain relief model of the island"),
   ("00:07.5-00:10", "one officer leans forward over the relief model, otherwise motionless")], 0.0),
 ("command", "slow arc around the relief-model table", "accident or attack",
  [("00:00-00:04", "the arc passes behind the officers; the lamp light falls on the grey relief model"),
   ("00:04-00:10", "a single small black pin stands on the relief model beside the island")], None),
 ("command", "the slow arc continues", "they chose to raise the ship",
  [("00:00-00:07", "the four officers stand still around the relief model as the arc continues"),
   ("00:07-00:10", "the arc comes round to the black pin on the relief model")], None),
 ("seabed_stern", "the lamp light fades and the view sinks into deep water, then a slow descent toward the stern", "45 metres down; recovery begins",
  [("00:00-00:01.5", "without any cut the lamp light fades and the view sinks through dark water down to the seabed"),
   ("00:01.5-00:04", "the broken stern lies on the muddy seabed in faint light"),
   ("00:04-00:10", "two divers descend along a guide rope toward it, torch beams sweeping")], 0.0),
 ("seabed_stern", "slow glide alongside the divers", "preserving evidence",
  [("00:00-00:03.5", "the divers glide slowly along the hull, torches held low"),
   ("00:03.5-00:10", "one diver sets a small yellow marker buoy on the silt beside a fragment of steel")], None),
 ("seabed_stern", "a slow tilt up from the torn edge toward the surface far above", "a crime scene; the lift begins",
  [("00:00-00:03", "a diver holds a torch on the torn steel edge"),
   ("00:03-00:06.5", "the camera tilts up: a heavy lifting cable descends from the pale surface far above"),
   ("00:06.5-00:10", "the cable's big hook reaches the stern section; the divers guide it slowly")], None),
 ("seabed_stern", "slow lateral glide over the wreck and the debris field", "divers mapping, photographing, collecting",
  [("00:00-00:03.5", "divers pass heavy chains under the stern section"),
   ("00:03.5-00:06.5", "other divers swim in a line over the debris field, torches sweeping"),
   ("00:06.5-00:10", "a diver lifts a small metal fragment from the silt into a mesh bag")], None),
 ("seabed_stern", "slow push-in through the silt haze", "murky water, poor visibility",
  [("00:00-00:03.5", "silt clouds rise and the torch beams turn into short hazy cones"),
   ("00:03.5-00:10", "a diver feels along the jagged steel with gloved hands in the haze")], None),
 ("salvage", "a rise along the taut chains up to the surface, then a slow wide move around the crane barge", "the stern is raised first",
  [("00:00-00:04", "the silt haze drifts over the broken hull; the chains above go taut"),
   ("00:04-00:05.5", "without any cut the camera rises along the taut chains up through the water and breaks the surface"),
   ("00:05.5-00:10", "the crane barge lifts the broken stern section out of the grey sea, water pouring off the torn steel")], 4.0),
 ("salvage", "slow push-in toward the lifted section", "the metal was bent outward",
  [("00:00-00:04", "on the barge deck, silhouetted investigators in hard hats watch the stern section rise"),
   ("00:04-00:10", "slow push-in to the torn edge: thick steel plates bent outward, peeled away from the hull")], None),
 ("salvage", "the push-in continues, then tilts down beneath the lifted section", "a single point of impact from below",
  [("00:00-00:02.5", "the push-in continues along the outward-bent plates"),
   ("00:02.5-00:10", "the camera tilts down beneath the lifted section: the keel is bent upward at one point, the damage centred there")], None),
 ("salvage", "slow glide under the section along the keel", "the signature of an underwater explosion",
  [("00:00-00:05", "the camera glides slowly under the section along the upward-bent keel, water dripping from it"),
   ("00:05-00:10", "the bend rises to a single peak where the keel was pushed upward")], None),
 ("salvage", "slow pull-back to a wide view of the barge", "a message written in steel",
  [("00:00-00:03.5", "wide view: the lifted stern section hangs from the crane above the barge deck, grey sea around"),
   ("00:03.5-00:10", "the section is lowered slowly onto blocks on the deck; small investigator silhouettes walk toward it")], None),
 ("table", "a push-in on a torn steel fragment that carries on into a lamp-lit evidence table", "recovery becomes investigation",
  [("00:00-00:02", "the camera moves in close to a torn steel fragment on the barge deck"),
   ("00:02-00:03.5", "without any cut the grey daylight gives way to a single hard lamp over a plain evidence table"),
   ("00:03.5-00:10", "on the table: fragments in clear plastic bags with blank white tags, a torn bent piece of hull steel, a ruler")], 2.0),
 ("table", "slow push-in, then a slow lateral drift along the table", "a physical record in the steel",
  [("00:00-00:04", "slow push-in to the torn steel under the lamp: bent grain, blackened edge"),
   ("00:04-00:10", "slow lateral drift along a row of bagged fragments with blank tags, neatly aligned")], None),
 ("table", "the lateral drift continues, then a slow rise above the table", "retrieving the story",
  [("00:00-00:07", "the drift continues along the row of bagged fragments"),
   ("00:07-00:10", "the camera rises slowly above the table: dozens of bagged fragments laid out in rows")], None),
 ("dock", "the rise continues and the lamp light widens into daylight over a naval dock", "the bow is raised; two halves on the dock",
  [("00:00-00:03", "the camera keeps rising above the rows of evidence"),
   ("00:03-00:04.5", "without any cut the lamp light widens into flat grey daylight over a naval dock"),
   ("00:04.5-00:10", "on the dock the raised bow section rests on blocks, a crane standing beside it")], 3.0),
 ("dock", "slow rising crane move along the dock", "the full geometry of the destruction",
  [("00:00-00:06", "the camera rises: bow and stern sections lie side by side on blocks with a wide clean gap between them, small investigator silhouettes between them"),
   ("00:06-00:10", "from higher up the two halves look like one ship cut in two")], None),
 ("dock", "a slow descent into the gap, then a glide along the torn edge", "a clean gap, as if sliced",
  [("00:00-00:04", "the camera descends into the gap between the two halves, torn edges on both sides"),
   ("00:04-00:10", "a slow glide along the torn edge: a long, almost straight line through the hull")], None),
 ("dock", "the glide continues, then a slow pull-back along the quay", "an international investigation group",
  [("00:00-00:03.5", "the glide continues along the torn edge"),
   ("00:03.5-00:10", "exactly six investigator silhouettes in different coats walk slowly along the dock toward the hull sections")], None),
 ("dock", "slow arc around the group of investigators", "United States, United Kingdom, Australia, Sweden",
  [("00:00-00:03", "the six investigators stop beside the hull and look up at it"),
   ("00:03-00:10", "slow arc around the group, the torn hull towering behind them")], None),
 ("dock", "the slow arc continues", "outside eyes for legitimacy",
  [("00:00-00:07.5", "two investigators point up at the bent steel; another stretches a long measuring tape along the hull"),
   ("00:07.5-00:10", "the arc continues slowly past the group")], None),
 ("table", "a push-in on the torn steel that carries on into the lamp-lit evidence table", "neutral forensic rigour",
  [("00:00-00:02", "the arc passes close to the torn steel"),
   ("00:02-00:03.5", "without any cut the steel fills the frame and the daylight gives way to a single hard lamp"),
   ("00:03.5-00:10", "calipers rest on a fragment on the evidence table; the lamp light rakes across its bent surface")], 2.0),
 ("underhull", "a slow push-in over the table whose lamp light dims into deep water beneath a ship", "external and underwater",
  [("00:00-00:05.5", "slow push-in over the evidence table, fragments in rows"),
   ("00:05.5-00:07", "without any cut the lamp light dims to darkness and the view becomes deep water"),
   ("00:07-00:10", "above, the long dark hull of a ship seen from underneath; the water is still")], 5.5),
 ("underhull", "slow glide beneath the hull toward the stern", "below the waterline, near the stern",
  [("00:00-00:03", "the camera glides slowly beneath the long dark hull toward the stern"),
   ("00:03-00:07", "under the stern: the dark shapes of propellers and rudder"),
   ("00:07-00:10", "a faint pale point of light appears in the water below the keel")], None),
 ("bubble", "a slow upward tilt along the keel", "force directed upward",
  [("00:00-00:04", "the camera tilts up along the keel toward the engine spaces"),
   ("00:04-00:10", "below the keel the pale point grows into a small glowing sphere of gas, silent")], None),
 ("bubble", "slow steady drift beside the bubble", "the bubble-jet effect",
  [("00:00-00:05", "the gas bubble swells slowly beneath the keel into a huge dark sphere with a pale glowing rim"),
   ("00:05-00:10", "the bubble keeps expanding without touching the hull; the hull above stays rigid")], None),
 ("bubble", "slow steady drift beside the bubble", "the bubble collapses",
  [("00:00-00:06", "the bubble reaches its full size, then slowly collapses inward"),
   ("00:06-00:10", "as it collapses, a narrow white jet of water forms at its top, pointing up at the keel")], None),
 ("bubble", "slow steady drift beneath the keel", "the jet snaps the keel",
  [("00:00-00:06.5", "the white jet punches straight up into the keel and the hull bends upward at that one point"),
   ("00:06.5-00:10", "the water clears; the upward bend in the keel remains; the camera keeps gliding")], None),
 ("seabed_debris", "the dark water opens onto the torch-lit seabed, then a slow glide over the debris field", "the evidence in the debris",
  [("00:00-00:01.5", "without any cut the dark water opens onto the torch-lit seabed"),
   ("00:01.5-00:10", "slow glide over the debris field; small yellow marker buoys stand on the silt")], 0.0),
 ("seabed_debris", "slow glide alongside the two divers", "they knew what to look for",
  [("00:00-00:05.5", "two divers sweep their torches across the silt in a slow grid"),
   ("00:05.5-00:10", "one diver stops and points a torch at a small twisted piece of metal")], None),
 ("seabed_debris", "slow push-in, then a slow lateral move along the silt", "pieces that did not belong to the ship",
  [("00:00-00:03", "close on the twisted metal, different from the grey hull steel"),
   ("00:03-00:10", "the torch beam moves across a coil of thin wire and small machined parts half-buried in silt")], None),
 ("torpedo_run", "the torch beam fades and the camera glides off into dark open water, then a slow tracking move", "a CHT-02D torpedo",
  [("00:00-00:05", "the torch beam lingers on the machined parts in the silt"),
   ("00:05-00:06.5", "without any cut the torch beam fades and the camera glides off into dark open water"),
   ("00:06.5-00:10", "a long dark torpedo slides past through the gloom, its propeller turning slowly")], 5.0),
 ("torpedo_run", "slow tracking alongside the torpedo", "a bubble-jet, wake-homing weapon",
  [("00:00-00:08", "the torpedo runs straight and steady through the dark water, a faint trail of tiny bubbles behind the propeller"),
   ("00:08-00:10", "far ahead and above, the pale churning wake of a ship's propellers comes into view")], None),
 ("torpedo_run", "the tracking move follows the torpedo upward", "it follows the wake to the stern",
  [("00:00-00:07", "the torpedo turns gently and follows the churning wake upward toward the dark stern of a ship above"),
   ("00:07-00:10", "it glides on beneath the stern's silhouette")], None),
 ("torpedo_run", "slow pull-back from the torpedo", "quiet, patient, precise",
  [("00:00-00:06", "the camera drifts back; the torpedo glides slowly, almost lazily, through the dark water"),
   ("00:06-00:10", "it holds a steady course, silent, beneath the faint wake above")], None),
 ("torpedo", "a slow sinking move past the torpedo down to the seabed", "the real discovery was still submerged",
  [("00:00-00:04.5", "the torpedo glides on through the dark water"),
   ("00:04.5-00:06", "without any cut the camera sinks past it toward the seabed"),
   ("00:06-00:10", "in the silt a corroded cylindrical shape lies half-buried, barely visible")], 4.5),
 ("torpedo", "slow push-in toward the propulsion section", "the propulsion section left behind",
  [("00:00-00:04", "slow push-in: the corroded propulsion section with its small crusted propeller"),
   ("00:04-00:10", "a diver's torch beam sweeps in from above and finds it")], None),
 ("torpedo", "slow rise alongside the lifted section", "divers recover it",
  [("00:00-00:08", "two divers work straps under the propulsion section and it lifts slowly from the silt on a line"),
   ("00:08-00:10", "it rises out of the torch beam toward the surface")], None),
 ("lab", "the rise continues up through the water into the hard work lights of a hangar, then a slow push-in", "something no one predicted",
  [("00:00-00:01.5", "without any cut the camera rises with it; the dark water gives way to hard work lights in a grey hangar"),
   ("00:01.5-00:05.5", "the corroded propulsion section rests on a padded stand, two investigator silhouettes beside it"),
   ("00:05.5-00:10", "slow push-in toward the inside of the casing")], 0.0),
 ("lab", "the slow push-in continues to the ink smudge", "a handwritten marking",
  [("00:00-00:08.5", "close: a faint smudge of blue ink on the pitted metal, blurred and illegible, lit by the hard lamp"),
   ("00:08.5-00:10", "the push-in continues slowly")], None),
 ("lab", "slow drift across the smudge, then a slow pull-back", "the torpedo signed its maker's name",
  [("00:00-00:04", "the camera drifts across the ink smudge; it stays an unreadable blur"),
   ("00:04-00:10", "the camera pulls back to the whole corroded section on its stand")], None),
 ("lab", "slow arc around the section", "it survived the blast, the corrosion, the months underwater",
  [("00:00-00:07.5", "slow arc around the section: pitted, rust-streaked metal, crusted propeller blades"),
   ("00:07.5-00:10", "the arc continues past the propeller")], None),
 ("lab", "the arc comes back round to the ink smudge", "a handwritten note on a weapon of war",
  [("00:00-00:09", "the camera returns slowly to the blurred ink smudge under the lamp; hard shadows in the pitted metal"),
   ("00:09-00:10", "the move continues slowly")], None),
 ("sub", "the lamp light fades into dark shallow water, then a slow approach toward the submarine", "fired from a Yeono-class midget submarine",
  [("00:00-00:04.5", "the ink smudge fills the frame under the lamp"),
   ("00:04.5-00:06", "without any cut the lamp light fades to darkness and the view becomes dark shallow water"),
   ("00:06-00:10", "a small dark midget submarine glides out of the murk toward the camera")], 4.5),
 ("sub_under", "slow tracking alongside the small submarine", "one-tenth the size of the ship it destroyed",
  [("00:00-00:04", "slow tracking alongside the small submarine: rounded hull, small fin, one propeller"),
   ("00:04-00:10", "far above, the dark silhouette of a much larger ship's hull passes over it along the surface")], None),
 ("sub", "slow tracking alongside the submarine between boulders", "small enough for the shallow littoral",
  [("00:00-00:08", "the submarine threads slowly between large boulders close to the seabed in shallow water"),
   ("00:08-00:10", "it glides over a low rocky ridge")], None),
 ("sub", "slow drift beside the submarine", "hard to detect against the cluttered seabed",
  [("00:00-00:07", "the submarine settles low among rocks and silt; its dark shape almost blends into the cluttered seabed"),
   ("00:07-00:10", "it moves on slowly")], None),
 ("sub", "a slow tilt up to the surface, then back down to the submarine", "diesel-electric, nearly silent on batteries",
  [("00:00-00:04.5", "the camera looks up: far above, the pale ceiling of the surface"),
   ("00:04.5-00:10", "the submarine glides on in total stillness; no bubbles, no disturbance in the silt")], None),
 ("sonar", "the dark water gives way to the green glow of a sonar display, then a slow push-in", "mistaken for a whale, fish, rough seabed",
  [("00:00-00:01.5", "without any cut the dark water gives way to the glow of a round green display"),
   ("00:01.5-00:08", "on the sonar display only faint grainy noise and a soft sweeping line; one vague blur appears and fades"),
   ("00:08-00:10", "the operator's silhouette leans in, headphones on")], 0.0),
 ("sonar", "slow push-in past the operator to the display", "almost no signature",
  [("00:00-00:04.5", "slow push-in past the operator to the display"),
   ("00:04.5-00:10", "the sweeping line passes again and again over nothing")], None),
 ("sub_under", "the green glow deepens into dark water, then a slow drift up toward the hull above", "the acoustic equivalent of a shadow",
  [("00:00-00:01.5", "the sweeping line passes over the empty screen"),
   ("00:01.5-00:03", "without any cut the green glow deepens into dark water"),
   ("00:03-00:10", "the small submarine glides slowly beneath the huge dark hull of the corvette passing along the surface above")], 1.5),
 ("sub_under", "slow drift near the seabed", "it only needed to outwait her",
  [("00:00-00:05", "the corvette's hull passes slowly overhead; the submarine stays still near the seabed"),
   ("00:05-00:10", "the hull moves away; the submarine waits, motionless")], None),
 ("sub_under", "slow pull-back and down", "an ambush, not a clash of equals",
  [("00:00-00:05", "the camera pulls back and down: the tiny submarine below, the huge hull far above"),
   ("00:05-00:10", "the submarine turns slowly to follow the fading wake")], None),
 ("lab", "the dark water gives way to the hard lamp of the hangar, then a slow push-in", "a weapon identified by hand",
  [("00:00-00:02.5", "the submarine glides on into the dark"),
   ("00:02.5-00:04", "without any cut the darkness gives way to the hard lamp of the investigation hangar"),
   ("00:04-00:10", "the corroded propulsion section on its stand, the blurred ink smudge in the lamp light")], 2.5),
 ("dock", "a slow pull-back out of the hangar into daylight over the dock", "the proof on the ocean floor",
  [("00:00-00:02", "the lamp light on the propulsion section"),
   ("00:02-00:03.5", "without any cut the camera pulls back out of the hangar into grey daylight over the dock"),
   ("00:03.5-00:10", "the two halves of Cheonan on the dock, a wide clean gap between them")], 2.0),
 ("report", "the daylight gives way to a press room, then a slow push-in toward the table", "20 May 2010: the report",
  [("00:00-00:01", "the two halves lie still on the dock"),
   ("00:01-00:02.5", "without any cut the grey daylight gives way to the flat light of a press room"),
   ("00:02.5-00:10", "a thick bound report with a blank cover lies closed on a long table before a row of microphones; blurred reporters beyond")], 1.0),
 ("report", "slow push-in toward the report", "a North Korean torpedo, a North Korean submarine",
  [("00:00-00:04", "slow push-in toward the report and the microphones"),
   ("00:04-00:10", "the blurred room stays still; the push-in continues to the report's blank cover")], None),
 ("radio", "the press-room light dims to a single amber glow, then a slow push-in", "Pyongyang denies it",
  [("00:00-00:04.5", "the push-in continues on the blank cover of the report"),
   ("00:04.5-00:06", "without any cut the room light dims to a single amber glow"),
   ("00:06-00:10", "an old radio receiver glows on a wooden table in a dark room")], 4.5),
 ("radio", "slow push-in toward the glowing radio", "a total, public denial",
  [("00:00-00:10", "slow push-in toward the radio; its amber dial glows steadily, dust drifting in the light")], None),
 ("radio", "slow arc around the radio", "a demand for their own investigators",
  [("00:00-00:08.5", "slow arc around the radio; its amber dial glows steadily in the dark"),
   ("00:08.5-00:10", "the arc continues")], None),
 ("radio", "slow drift past the radio into darkness", "the denial never wavered",
  [("00:00-00:05", "the camera drifts slowly past the radio into the dark room"),
   ("00:05-00:10", "only the amber glow remains")], None),
 ("study", "the amber glow widens into a desk lamp, then a slow push-in", "a minority of academics had doubts",
  [("00:00-00:00.5", "the amber glow in the dark"),
   ("00:00.5-00:02", "without any cut the amber glow widens into a desk lamp in a quiet study"),
   ("00:02-00:10", "one silhouetted figure sits at the desk, one hand resting on the closed report under the lamp")], 0.5),
 ("study", "slow push-in over the figure's shoulder", "did the evidence prove it",
  [("00:00-00:04", "slow push-in over the figure's shoulder to the small scale model of the broken hull"),
   ("00:04-00:10", "the figure leans back and stays still, the lamp light on the scale model")], None),
 ("study", "slow arc around the desk", "too quick from explosion to attribution",
  [("00:00-00:06", "slow arc around the desk; the closed report and the scale model under the lamp"),
   ("00:06-00:10", "the arc continues toward the dark window")], None),
 ("sonar", "through the dark window the view becomes the green glow of a sonar display", "no direct contact was ever established",
  [("00:00-00:00.5", "the arc reaches the dark window"),
   ("00:00.5-00:02", "without any cut the dark window becomes the green glow of a sonar display"),
   ("00:02-00:10", "the sonar display shows only faint noise and a sweeping line, nothing, again and again")], 0.5),
 ("mine", "the green glow fades into murky water, then a slow drift toward the mine", "other explanations",
  [("00:00-00:02.5", "the sweeping line passes over the empty screen"),
   ("00:02.5-00:04", "without any cut the green glow fades into murky green water"),
   ("00:04-00:10", "an old rusted spiked sea mine sways slowly on its chain in the murk")], 2.5),
 ("mine", "slow arc around the mine, then a drift away", "a minority view",
  [("00:00-00:06", "slow arc around the rusted mine: crusted spikes, its chain vanishing into the silt"),
   ("00:06-00:10", "the camera drifts away from the mine into the murk")], None),
 ("table", "the murk gives way to the evidence table, then a slow lateral drift", "the world had the evidence",
  [("00:00-00:05", "the murk drifts past the camera"),
   ("00:05-00:06.5", "without any cut the murk gives way to the hard lamp over the evidence table"),
   ("00:06.5-00:10", "rows of bagged fragments with blank tags under the lamp")], 5.0),
 ("un", "a rise from the table into the soft daylight of a council chamber, then a slow glide", "the UN Security Council statement",
  [("00:00-00:02.5", "the drift continues along the bagged fragments"),
   ("00:02.5-00:04", "without any cut the camera rises and the lamp light opens into the soft daylight of a large council chamber"),
   ("00:04-00:10", "a wide circular chamber: a horseshoe table with rows of chairs and microphones, blurred distant figures")], 2.5),
 ("un", "slow glide along the curve of the table", "it condemned the attack but named no one",
  [("00:00-00:04.5", "slow glide along the curve of the horseshoe table, microphones and empty chairs"),
   ("00:04.5-00:10", "the glide continues past one empty chair")], None),
 ("un", "slow rise above the chamber", "careful diplomatic language",
  [("00:00-00:07.5", "the camera rises slowly above the chamber"),
   ("00:07.5-00:10", "the whole horseshoe table seen from above")], None),
 ("lab", "the chamber light narrows into the hard lamp of the hangar, then a slow push-in", "forensic certainty, diplomatic silence",
  [("00:00-00:04.5", "the horseshoe table seen from above"),
   ("00:04.5-00:06", "without any cut the soft daylight narrows into the hard lamp of the hangar"),
   ("00:06-00:10", "the corroded propulsion section on its stand, the blurred ink smudge")], 4.5),
 ("lab", "slow push-in to the ink smudge", "not enough to make the world say it",
  [("00:00-00:07.5", "slow push-in toward the blurred ink smudge"),
   ("00:07.5-00:10", "the push-in continues")], None),
 ("torpedo", "the lamp light fades into dark water and the torch-lit seabed, then a slow drift", "it signed its maker's name on the seabed",
  [("00:00-00:02", "the ink smudge fills the frame"),
   ("00:02-00:03.5", "without any cut the lamp light fades into dark water and a torch-lit seabed"),
   ("00:03.5-00:10", "the silt where the propulsion section was found; a small yellow marker buoy stands alone")], 2.0),
 ("memorial", "a steady rise up through the water to the surface at dusk, then a slow drift toward the wreath", "a marking outlasts a denial",
  [("00:00-00:00.5", "the marker buoy on the silt"),
   ("00:00.5-00:02", "without any cut the camera rises up through the dark water and breaks the surface at dusk"),
   ("00:02-00:10", "calm grey sea at dusk off the barren island; a single white wreath floats on the water")], 0.5),
 ("memorial", "slow rising pull-back", "subscribe and stay with us",
  [("00:00-00:10", "slow rising pull-back: the wreath small on the wide grey sea, the island beyond, dusk falling")], None),
]


def main():
    assert len(C) == 100, len(C)
    clips, prev = [], "standoff"
    for i, (sid, camera, action, beats, chg) in enumerate(C):
        s, p = SETS[sid], SETS[prev]
        if chg is not None:
            t = f"00:{int(chg):02d}" + (".5" if chg % 1 else "")
            env = f"{p['env']} -- then -- {s['env']}"
            cast = f"{p['cast']} (until {t}); then {s['cast']}"
            light = f"{p['light']}; then {s['light']}"
            neg = ", ".join(x for x in (p.get("neg"), s.get("neg")) if x)
            rigid = "; ".join(x for x in (p.get("rigid"), s.get("rigid")) if x)
        else:
            env, cast, light, neg, rigid = s["env"], s["cast"], s["light"], s.get("neg"), s.get("rigid")
        clip = {"env": env, "cast": cast, "action": action, "camera": camera, "lighting": light,
                "beats": [list(b) for b in beats]}
        if chg is not None:
            clip["change_at"] = chg
        if neg:
            clip["neg"] = neg
        if rigid:
            clip["rigid"] = rigid
        clips.append(clip)
        prev = sid
    plan = {"tag": "CH02EP16", "look": "ch02", "start": 13, "clips": clips}
    p = HERE / "CH02EP16_omni_plan_013-112.json"
    p.write_text(json.dumps(plan, ensure_ascii=False, indent=1), encoding="utf-8")
    render = HERE / "_rx_omni_render.py"
    if not render.exists():
        render = HERE.parent / "_rx_omni_render.py"
    subprocess.run([sys.executable, str(render), str(p)], check=True)


if __name__ == "__main__":
    main()
